### ISSUE TITLE
возможная гонка в userstats/paycards

### ISSUE THREAD

**Issue by alex-eri** [nightflyza/Ubilling#130]
При быстром запросе на медленный сервер получается выполнение команд в таком порядке:

з1: zbs_PaycardCheck
з2: zbs_PaycardCheck
з2: zbs_PaycardUse
з1: zbs_PaycardUsе

Снова неистовые запрсы )

**Comment by nightflyza** [comment]
Ок.

**Comment by alex-eri** [comment]
пока не решено
