### ISSUE TITLE
Notice: Undefined index: ONUREG_ZTE 

### ISSUE THREAD

**Issue by pautiina** [nightflyza/Ubilling#165]
Выдает в браузере: 
Notice: Undefined index: ONUREG_ZTE in `/api/libs/api.pon.php on line 1373`

**Comment by nightflyza** [comment]
http://wiki.ubilling.net.ua/doku.php?id=relnotes

**Comment by pautiina** [comment]
Ссори, то у меня ошибка выскакиват на develop ветке. Там не все применяю :)

**Comment by nightflyza** [comment]
ССЗБ же
