### ISSUE TITLE
Логика опции CONTRACT_PROFILE_HIDE 

### ISSUE THREAD

**Issue by pautiina** [nightflyza/Ubilling#259]
https://github.com/nightflyza/Ubilling/blob/6aea551e1cb47eee6929c73218b81b6a42874c51/api/libs/api.userprofile.php#L1249

Как бы опция не обязательное, но если ее не будет в конфиге, то все номера договоров прячутся

**Comment by nightflyza** [comment]
Пуллреквест вижу, ща закончу допиливать свои заказы и померджу.
