### ISSUE TITLE
При ручном обработке оплат OPANPAYZ - вылазят ошибки

### ISSUE THREAD

**Issue by pautiina** [nightflyza/Ubilling#264]
![image](https://user-images.githubusercontent.com/11805503/41157106-34eed890-6b2d-11e8-8c44-10aeaad7d7da.png)

**Comment by nightflyza** [comment]
Ок, ща пофиксю. Сто лет этим не пользовался.

**Comment by nightflyza** [comment]
Исправил на скорую руку в bdda9fe8c072cd56dc5997f672b44714b03bbeb4
