### ISSUE TITLE
Модуль "Живи с этим" - не предусмотрено возможность выбора типа оплаты

### ISSUE THREAD

**Issue by pautiina** [nightflyza/Ubilling#281]
Короче приходиться создавать вопрос, так-как не могу до конца понять, как это реализовать без нарушения структуры кода.
У меня только есть два варианта и оба они мне не нравятся:
- в базу данных загонять сериализованный массив вида: `a:2:{s:1:"s";s:5:"10000";s:1:"c";s:4:"1000";}` , но тут появляется проблема поля `param` => 'VARCHAR(45)'. Данная строка влезит, но если мы захотим на 100000 тугриков пополнить - получим MySQL error. Также придется для визуализации дописывать код, чтобы в таблице результатов выводилось нормальные данные, а это ломает всю структуру кода.
- в базу данных добавить столбец `param2` и снова придется ломать структуру кода. 

Хотелось бы услышать ваши предложения.

**Comment by nightflyza** [comment]
Я уже говорил, что ты умеешь находить самые неочевидные, трудоемкие и сложные решения из возможных? :)

Короче ща допью кофе, доеду до работы и сделаю тебе типы оплат для одиночных задач. На свои "массовые беспорядки" экстраполируешь сам.
