### ISSUE TITLE
Есть сомнения, что вызов freezedayscharge через RemoteAPI вообще работает

### ISSUE THREAD

**Issue by pautiina** [nightflyza/Ubilling#319]
https://github.com/nightflyza/Ubilling/blob/10d9802bcca79a1a95f6e7194a27cff1bd9b7519/modules/general/remoteapi/index.php#L456

я не проверял, но что-то мне кажется что оно не работает.
Так-же не мешало бы SQL запросы убрать с этого файла.

**Comment by bobr-kun** [comment]
Ээээм - ну у меня - работает, дни считает. А откуда, собственно, сомнения?
И куда предлагаешь вынести SQL-запросы?

**Comment by pautiina** [comment]
Вставь этот запрос:
```
SELECT `frozen_charge_days`.`*`, `users`.`Passive`, `users`.`Down`, `users`.`Credit`, `users`.`Cash` 
                                                  FROM `frozen_charge_days`
                                                    LEFT JOIN `users` ON `frozen_charge_days`.`login` = `users`.`login`
```
в консоль разработчика ->SQL консоль.
Запросы вообще предлагаю в функции вынести.

**Comment by bobr-kun** [comment]
![default](https://user-images.githubusercontent.com/21010732/45499981-2c356e80-b786-11e8-8810-b39bc4888406.png)
вот как бы и данные...

>>Запросы вообще предлагаю в функции вынести.
эмммм.... а функции будут находиться тут же, в remoteapi? 
а вообще - в remoteapi довольно много plain-text SQL-запросов юзается. мои что - самые лысые, чтобы их лично куда-то отдельно выносить?

**Comment by pautiina** [comment]
А вот так у меня:
![image](https://user-images.githubusercontent.com/11805503/45503414-72db9680-b78f-11e8-916a-82fce93dd215.png)
а если сделать так:
```
SELECT `frozen_charge_days`.*, `users`.`Passive`, `users`.`Down`, `users`.`Credit`, `users`.`Cash` 
                                                  FROM `frozen_charge_days`
                                                    LEFT JOIN `users` ON `frozen_charge_days`.`login` = `users`.`login`
```
то и у меня и у остальных заработает.
Даю подсказку:
```
`frozen_charge_days`.*,
```

**Comment by bobr-kun** [comment]
Хм... А почему же у меня `*` - работает?
Что это за хитрая настройка у меня включена(или выключена)?

**Comment by pautiina** [comment]
Версию мускула, и настройки my.cnf в студию

**Comment by pautiina** [comment]
Fixed https://github.com/nightflyza/Ubilling/pull/318
