### ISSUE TITLE
Добавить возможность рассылки СМС пополнившимся

### ISSUE THREAD

**Issue by pautiina** [nightflyza/Ubilling#324]
Добавить возможность отсылать СМС тем, кто-то внес деньги на счет.

**Comment by nightflyza** [comment]
Это делается при желании хоть One-Punch скриптом, хоть вызовом single-функции из remoteapi. Просто следует отслеживать состояние payments в каком-то временном интервале, либо мониторить изменения Cash в users.

**Comment by pautiina** [comment]
Решилось ПУШ-скриптом

**Comment by nightflyza** [comment]
Я знал, что ты иногда умеешь не заморачиваться и использовать простые решения. Признавайся в сколько строк уложился? ;)

**Comment by nightflyza** [comment]
И как, понравилось? ;)

**Comment by pautiina** [comment]
>И как, понравилось? ;)
Ага. Главное что работает
