### ISSUE TITLE
envy module bug

### ISSUE THREAD

**Issue by beeonlinecy** [nightflyza/Ubilling#609]
When a password to a device contains symbols (Checked with ']') , the script returns nothing

**Comment by nightflyza** [comment]
Thats not a bug. 
For passwords or another envy-scripts input data, any filtering not provided. All data will be pushed to temporary polling scripts just "as is".

If your passwords contains some chars which is contains patterns or another control symbols of expect, you always can to escape your passwords data with "\" symol. Just like !@#$%^{}[]  must be filled for envy-device as !@#$%^{}\[\]
