### ISSUE TITLE
OpenPayz: теперь теоретически может работать на PHP 7.

### ISSUE THREAD

**Issue by pautiina** [nightflyza/Ubilling#67]
LiqPAY пока работать не будет.
Оставил для напоминания, то нужно исправить.

**Comment by nightflyza** [comment]
Почему? Если изза mysql_real_escape_string, то мы вроде как успешно его изображаем? 

https://github.com/nightflyza/Ubilling/blob/master/openpayz/libs/api.mysql.php#L55

**Comment by pautiina** [comment]
Совершенно верно,  мы ее изображаем, но бекенды нигде не подключают app.MySQL - по этому они об этой функции не знают. mysql_real_escape_string есть только функция у бекенда Liqpay, в остальных бекендах ее нет. По этому и не работает. Проверено.

**Comment by nightflyza** [comment]
> Совершенно верно, мы ее изображаем, но бекенды нигде не подключают app.MySQL
э-э-э... я этого как-то и не заметил :)

**Comment by nightflyza** [comment]
Исправлено в pullrequest #70
