### ISSUE TITLE
Не работает remote api

### ISSUE THREAD

**Issue by alex-eri** [nightflyza/Ubilling#7]
Делаем 
curl "http://127.0.0.1/billing/?module=remoteapi&key=XXX&action=reset+5"
а в ответ форма входа в админку. Версия 0.7.3 rev 4912

**Comment by alex-eri** [comment]
http://127.0.0.1/billing/?module=remoteapi&key=XXX&action=reset&param=5"
так правильней, но всеже вывод начальной страницы вместо ошибки присутствует.

**Comment by nightflyza** [comment]
Передаем привет вашему 0.7.3. Его давно не существует в природе. В любом случае, http://host/?module=remoteapi&key=UBxxxxxx&action=reset&param=login успешно себе работает, говоря при этом OK:RESET, и там ничего не менялось уже неизвестно сколько.
