### ISSUE TITLE
Feature request BSDRP/openbsd

### ISSUE THREAD

**Issue by joeshua** [nightflyza/Ubilling#790]
In radius NAS can you add BSDRP/openbsd as router and pull data from API/ABI would be great thanks.

**Comment by nightflyza** [comment]
![Wat8](https://user-images.githubusercontent.com/1496954/221353977-d2838109-cbd8-4071-8748-de392df9e102.jpg)

**Comment by joeshua** [comment]
Like you have pfsense, mikrotik can you or in future add bsdrp ?
[https://bsdrp.net/](url)

**Comment by pautiina** [comment]
BSDRP - норм тема.

**Comment by nightflyza** [comment]
> BSDRP - норм тема.

давай, дєрзай, я в тебе вірю! :)

P.S. А що, воно може в BRAS-ування?

**Comment by ocochard** [comment]
BSDRP includes mdp5, so the existing documentation should works: https://wiki.ubilling.net.ua/doku.php?id=mgmpdppp
(I didn't test it)
