### ISSUE TITLE
Ubilling 2.0: BLAZINGLY FAST NEEDED

### ISSUE THREAD

**Issue by Puz1kTelepuz1k** [nightflyza/Ubilling#825]
Rust is a great language, we can make Ubilling very very fast and fashionable
php have poor performance.

This's amazing choice. Why not? 
https://github.com/nightflyza/Ubilling/pull/824

**Comment by nightflyza** [comment]
Rejected. Your mom is not proud of you.

**Comment by Puz1kTelepuz1k** [comment]
Why?
