### ISSUE TITLE
Ubilling 2.0: NEED BLAZINGLY FAST

### ISSUE THREAD

**Issue by Puz1kTelepuz1k** [nightflyza/Ubilling#826]
**Describe the bug**
Ubilling is slow - because of php
#824 

**To Reproduce**
1. Go to 'https://demo.ubilling.net.ua'
2. Click on 'login'
3. Enjoy bad performance

**Expected behavior**
Blazingly fast open

**Additional context**
You closed a PR with #824 so try again

**Comment by nightflyza** [comment]
Rejected. Your mom is not proud of you.

**Comment by Puz1kTelepuz1k** [comment]
Why?
