### ISSUE TITLE
Ошибка при рассылке СМС

### ISSUE THREAD

**Issue by pautiina** [nightflyza/Ubilling#85]
Вот ссылка на форуме: [https://local.com.ua/forum/topic/97766-ubilling-083-rev-5567-рассылка-sms/](Локал):
Вот ошибка вывода:

`Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in /var/www/data/billing.*.*.ua/api/libs/api.dbconnect.php:116 Stack trace: #0 `

Создал, чтобы не забыть решить проблему.

**Comment by nightflyza** [comment]
А фиг его знает. Собака вроде способна послать несколько СМС, а дальше - пофиг :)
