### ISSUE TITLE
Поломался модуль задач

### ISSUE THREAD

**Issue by pautiina** [nightflyza/Ubilling#95]
![default](https://user-images.githubusercontent.com/11805503/28412989-9a4369aa-6d4e-11e7-9842-9767b79a4964.png)

**Comment by pautiina** [comment]
Туплю- пора в отпуск:)
![default](https://user-images.githubusercontent.com/11805503/28413199-64d6ac86-6d4f-11e7-9084-ccd7e7ab72d5.png)

**Comment by nightflyza** [comment]
100% пора. Я вот уже лет 5 как мечтаю.
